name: 'Spellcheck'
on:
  pull_request:
    paths: ['src/**', '**/*.md']

permissions:
  pull-requests: read

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          persist-credentials: false

      - uses: streetsidesoftware/cspell-action@d4c3df16cdd0faebccb1711178a8a490966f61b9
        name: Documentation spellcheck
        if: ${{ !cancelled() }}
        with:
            files: '**/*.md'
            inline: error
            incremental_files_only: true

      - uses: streetsidesoftware/cspell-action@d4c3df16cdd0faebccb1711178a8a490966f61b9
        name: Resx spellcheck
        if: ${{ !cancelled() }}
        with:
            files: 'src/**/*.resx'
            inline: error
            incremental_files_only: true

      - uses: streetsidesoftware/cspell-action@d4c3df16cdd0faebccb1711178a8a490966f61b9
        name: Source code spellcheck
        if: ${{ !cancelled() }}
        with:
            files: 'src/**/*{.cs,.cpp,.h,.targets,.props,.*proj}'
            inline: warning
            incremental_files_only: true
            # Do not cause the gate to fail if potential typos in source code are found.
            # The signal-to-noise ratio here needs to be better understood first.
            strict: false
